#!/usr/bin/env node
/**
 * Writes build provenance into `apps/<app>/.env.production.local` so Next.js
 * inlines `NEXT_PUBLIC_BUILD_SHA` and `NEXT_PUBLIC_BUILD_DATE` at build time.
 *
 * Invoked as a prebuild step from:
 *   - apps/desktop: `pnpm pack` (before `next build`)
 *   - apps/web:     Dockerfile (before `pnpm --filter @florin/web build`)
 *
 * Dev builds (where this script isn't run) see `undefined` for both vars;
 * the UI falls back to 'dev' / '—'. `.env.production.local` is gitignored.
 *
 * Usage: node scripts/build-info.mjs <desktop|web>
 */
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const app = process.argv[2]
if (app !== 'desktop' && app !== 'web') {
  console.error('Usage: node scripts/build-info.mjs <desktop|web>')
  process.exit(1)
}

let sha = 'dev'
try {
  sha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim()
} catch {
  // No git (e.g. tarball build context) — fall through to 'dev'.
}

const date = new Date().toISOString()
const envPath = resolve(process.cwd(), `apps/${app}/.env.production.local`)
const content = `# Auto-generated by scripts/build-info.mjs — do not edit.\nNEXT_PUBLIC_BUILD_SHA=${sha}\nNEXT_PUBLIC_BUILD_DATE=${date}\n`

writeFileSync(envPath, content)
console.log(`[build-info] ${app}: sha=${sha} date=${date}`)
