#!/usr/bin/env python3
"""
One-shot migrator (reverse of sqlite-to-pg-dump.py): turns a PostgreSQL
`pg_dump --data-only --column-inserts` stream into a SQLite import script
that wipes the desktop data tables and re-inserts every row from the web
deployment. Pulls the self-hosted web instance's data set onto the
Mac desktop.

Why a transform instead of a live connection: the web Postgres runs inside
a docker container behind an LXC, so there's no direct psycopg2 reach. We
let `pg_dump` do the (correctly-escaped) heavy lifting and just reshape its
output for SQLite. The two schemas (packages/db-pg/src/schema.ts vs
packages/db-sqlite/src/schema.ts) share column names, so --column-inserts
maps by name and column order never matters.

Things this handles:
  - Strips the `public.` schema prefix Postgres emits.
  - Keeps only the shared data tables; drops `users` and
    `__drizzle_migrations` (desktop has no auth, owns its own migrations).
  - Leaves the desktop-only `settings` table untouched (EB app id +
    private-key path live there) by simply never deleting it.
  - Postgres booleans (`true`/`false`) and the dump's timestamp text
    format both pass straight through: SQLite 3.23+ coerces TRUE/FALSE to
    1/0 on INTEGER columns, and the desktop already stores timestamps in
    Postgres' text format.

Usage (full pipeline from a Mac):
    # Run pg_dump on the host where the web Postgres container lives. If it's
    # local, drop the ssh prefix; if it's remote, wrap with `ssh user@your-server`.
    docker exec florin-db \\
      pg_dump -U florin -d florin --data-only --column-inserts --no-owner \\
      | python3 scripts/pg-to-sqlite-dump.py > /tmp/florin_import.sql

    DB="$HOME/Library/Application Support/@florin/desktop/florin.db"
    cp "$DB" "$DB.backup-$(date +%Y%m%d-%H%M%S)"   # always back up first
    sqlite3 "$DB" < /tmp/florin_import.sql          # desktop app must be closed

You can also pass the dump as a file argument instead of stdin:
    python3 scripts/pg-to-sqlite-dump.py raw_pg_dump.sql > import.sql

Stop-gap until proper bidirectional sync is built between desktop SQLite
and web PostgreSQL.
"""

from __future__ import annotations

import re
import sys

# Shared data tables. Listed child-first so the DELETEs read in FK order;
# inserts come straight from pg_dump (parent-first) and run with foreign
# keys off anyway, so ordering is belt-and-suspenders, not load-bearing.
TABLES_DELETE_ORDER = [
    'bank_sync_account_results',
    'bank_sync_runs',
    'balance_snapshots',
    'monthly_budgets',
    'categorization_rules',
    'holdings',
    'transactions',
    'categories',
    'category_groups',
    'accounts',
    'bank_connections',
]

# Postgres tables we never import: desktop has no auth and manages its own
# migration ledger. `settings` is desktop-only and simply absent from PG.
SKIP_TABLES = {'users', '__drizzle_migrations'}

INSERT_RE = re.compile(r'^INSERT INTO public\.([a-zA-Z_]+) ')


def transform(lines) -> tuple[list[str], dict[str, int]]:
    counts: dict[str, int] = {t: 0 for t in TABLES_DELETE_ORDER}
    inserts: list[str] = []
    for line in lines:
        m = INSERT_RE.match(line)
        if not m:
            continue
        table = m.group(1)
        if table in SKIP_TABLES:
            continue
        if table not in counts:
            # An unexpected table in the dump — surface it loudly rather
            # than silently importing or dropping it.
            print(f'WARNING: unknown table in dump, skipping: {table}',
                  file=sys.stderr)
            continue
        counts[table] += 1
        inserts.append(line.replace('INSERT INTO public.', 'INSERT INTO ', 1).rstrip('\n'))
    return inserts, counts


def main() -> int:
    if len(sys.argv) > 2:
        print('usage: pg-to-sqlite-dump.py [raw_pg_dump.sql] < dump > import.sql',
              file=sys.stderr)
        return 1

    src = open(sys.argv[1], encoding='utf-8') if len(sys.argv) == 2 else sys.stdin
    try:
        inserts, counts = transform(src)
    finally:
        if src is not sys.stdin:
            src.close()

    if not inserts:
        print('ERROR: no INSERT statements found. Did you pass '
              '`pg_dump --data-only --column-inserts` output?', file=sys.stderr)
        return 2

    out = sys.stdout
    out.write('-- Generated by scripts/pg-to-sqlite-dump.py\n')
    out.write('-- Imports web PostgreSQL data into desktop SQLite.\n')
    out.write('-- Wipes the shared data tables; leaves settings/users alone.\n\n')
    out.write('PRAGMA foreign_keys=OFF;\n')
    out.write('BEGIN;\n')
    for t in TABLES_DELETE_ORDER:
        out.write(f'DELETE FROM "{t}";\n')
    out.write('\n')
    out.write('\n'.join(inserts))
    out.write('\n\nCOMMIT;\n')

    total = sum(counts.values())
    print('Wrote import script:', file=sys.stderr)
    for t in TABLES_DELETE_ORDER:
        print(f'  {t}: {counts[t]}', file=sys.stderr)
    print(f'  total: {total} rows', file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
