#!/usr/bin/env python3
"""
One-shot migrator: reads the desktop SQLite db and emits a PostgreSQL
SQL dump that wipes the web schema (TRUNCATE CASCADE) and re-inserts
every row from SQLite. Pushes the Mac desktop's data set onto the
self-hosted Asgard web instance.

Usage:
    python3 scripts/sqlite-to-pg-dump.py <sqlite-path> <output.sql>

Then on the server:
    docker exec -i florin-db psql -U florin -d florin < output.sql

The two schemas (packages/db-pg/src/schema.ts vs packages/db-sqlite/
src/schema.ts) intentionally share column names. Differences this
script handles:
  - SQLite booleans are 0/1 INTEGER → PG wants TRUE / FALSE.
  - SQLite stores timestamps + dates as ISO TEXT → PG parses ISO natively.
  - The desktop-only `settings` table doesn't exist in PG → skipped.
  - `users` is empty on desktop (no auth) → skipped.
"""

from __future__ import annotations

import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path


# Insert order honours FKs: parents first, children last.
TABLES = [
    'bank_connections',
    'accounts',
    'category_groups',
    'categories',
    'transactions',
    'balance_snapshots',
    'categorization_rules',
    'monthly_budgets',
    'bank_sync_runs',
    'bank_sync_account_results',
]

# Columns stored as INTEGER 0/1 in SQLite but BOOLEAN in PG.
BOOLEAN_COLS: dict[str, set[str]] = {
    'accounts': {'is_active', 'is_archived', 'is_included_in_net_worth'},
    'categories': {'is_fixed', 'is_archived'},
    'transactions': {'is_pending', 'needs_review'},
    'categorization_rules': {'is_active'},
    'bank_sync_account_results': {'balance_fetched'},
}


def quote(value, is_boolean: bool) -> str:
    if value is None:
        return 'NULL'
    if is_boolean:
        return 'TRUE' if value else 'FALSE'
    if isinstance(value, bool):  # bool before int (bool is a subclass of int)
        return 'TRUE' if value else 'FALSE'
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (bytes, bytearray)):
        return "'\\x" + bytes(value).hex() + "'"
    # Default: str. Escape single quotes by doubling them.
    s = str(value).replace("'", "''")
    return f"'{s}'"


def dump_table(conn: sqlite3.Connection, table: str) -> str:
    cols = [r[1] for r in conn.execute(f'PRAGMA table_info({table})').fetchall()]
    rows = conn.execute(f'SELECT * FROM {table}').fetchall()
    bools = BOOLEAN_COLS.get(table, set())

    if not rows:
        return f'-- {table}: 0 rows\n'

    col_list = ', '.join(f'"{c}"' for c in cols)
    out = [f'-- {table}: {len(rows)} rows']
    for row in rows:
        vals = ', '.join(quote(row[i], cols[i] in bools) for i in range(len(cols)))
        out.append(f'INSERT INTO "{table}" ({col_list}) VALUES ({vals});')
    return '\n'.join(out) + '\n'


def main() -> int:
    if len(sys.argv) != 3:
        print('usage: sqlite-to-pg-dump.py <sqlite-path> <output.sql>', file=sys.stderr)
        return 1

    sqlite_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    conn = sqlite3.connect(f'file:{sqlite_path}?mode=ro', uri=True)
    try:
        chunks: list[str] = []
        chunks.append('-- Generated by scripts/sqlite-to-pg-dump.py')
        chunks.append(f'-- Source: {sqlite_path}')
        chunks.append(f'-- Generated: {datetime.now(timezone.utc).isoformat()}')
        chunks.append('')
        chunks.append('BEGIN;')
        chunks.append('')
        chunks.append('-- Wipe everything. CASCADE handles FK dependencies in one shot.')
        truncate_list = ', '.join(f'"{t}"' for t in TABLES)
        chunks.append(f'TRUNCATE {truncate_list} RESTART IDENTITY CASCADE;')
        chunks.append('')

        for t in TABLES:
            chunks.append(dump_table(conn, t))

        chunks.append('COMMIT;')
        chunks.append('')

        out_path.write_text('\n'.join(chunks), encoding='utf-8')

        print(f'Wrote {out_path}:')
        for t in TABLES:
            count = conn.execute(f'SELECT COUNT(*) FROM {t}').fetchone()[0]
            print(f'  {t}: {count}')
    finally:
        conn.close()

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
